Toasts
trimble-oss/modus-mobile-maui-components pull request #101
Opened 2023-06-05 06:13 UTC by ElishaSamPeterPrabhu

Add Dismissable Property
#78

2023-06-05 06:50 UTC, BAL4-R approved these changes

2023-06-05 08:58 UTC, rthanga1 requested changes
isDismissable should work only when the action label is null or empty.
1. So when the action label is given, then the action button will be displayed. Clicking that will close the toast and also calls the action.
2. When the action label is empty, then X button will be shown only when the isDismissable is true.

So basically, I think we should rephrase this. Let's discuss once you are in.

2023-06-05 10:29 UTC, rthanga1 approved these changes

2023-06-06 07:31 UTC, rthanga1 submitted a review, later dismissed

2023-06-06 09:04 UTC, Sofiya-kumar requested changes
Please have the toast as single file

2023-06-06 09:04 UTC, Sofiya-kumar requested changes
Please have the toast as single file

2023-06-06 09:06 UTC, Sofiya-kumar requested changes

2023-06-06 09:06 UTC, Sofiya-kumar commented on Trimble.Modus.Components/Controls/Toast/TMToast.cs
> +        private PopupNavigation popupNavigation;
Add regions

2023-06-06 10:10 UTC, ElishaSamPeterPrabhu commented on Trimble.Modus.Components/Controls/Toast/TMToast.cs
> +        private PopupNavigation popupNavigation;
Added

2023-06-06 10:11 UTC, ElishaSamPeterPrabhu commented
> Please have the toast as single file

Using a single file will allow the user to have access to the toasts contents page and can display it as a whole page , unlike now were they can access it only via show()

2023-06-06 10:36 UTC, Sofiya-kumar approved these changes

2023-06-06 11:08 UTC, rthanga1 approved these changes

2023-06-06 11:08 UTC, rthanga1 approved these changes

2023-06-06 12:04 UTC, merged