Add Loading feature button
trimble-oss/modus-mobile-maui-components pull request #270
Opened 2023-10-18 12:14 UTC by ElishaSamPeterPrabhu

![Screenshot_1697631135](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/676c8cda-5005-437f-bd35-f02d97d1ccad)

![Screenshot_1697631132](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/2c0c00d0-43a5-48c9-b37e-4ff91edfc482)
![Screenshot_1697631128](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/54122f0b-1c1f-4563-bbcd-e8564873fdd2)
![Screenshot_1697631125](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/1757c3c8-4126-46bf-b09c-529d69d52480)

2023-10-18 13:16 UTC, rthanga1 requested changes

2023-10-19 05:27 UTC, ElishaSamPeterPrabhu commented on DemoApp/DemoApp/Views/ButtonSamplePage.xaml
> +                                 IsLoading="{Binding IsLoading}"
Yes, changed it

2023-10-19 05:27 UTC, ElishaSamPeterPrabhu commented on DemoApp/DemoApp/Views/ButtonSamplePage.xaml
> +                Toggled="isLoading_Toggled" />
Yes, removed IsToggled Property.

2023-10-19 05:36 UTC, ElishaSamPeterPrabhu commented on Trimble.Modus.Components/Controls/Button/TMButton.xaml.cs
> +    private static void disableButton(bool toggleDisable,TMButton button)
Yes, changed

2023-10-19 05:43 UTC, ElishaSamPeterPrabhu commented on DemoApp/DemoApp/Views/ButtonSamplePage.xaml
> +        <Switch Grid.Column="3"
Yes, changed

2023-10-19 08:26 UTC, rthanga1 approved these changes

2023-10-19 09:16 UTC, merged