Add Left Right Views for input
trimble-oss/modus-mobile-maui-components pull request #271
Opened 2023-10-19 10:14 UTC by ElishaSamPeterPrabhu

![Screenshot_1697710457](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/344c0c27-e581-47cf-b78f-07bdd9288fc2)

2023-10-20 09:59 UTC, rthanga1 requested changes

2023-10-20 09:59 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMInput/TMInput.xaml
> +                 Content="{Binding RightCustomContent}">
Still says `RightCustomContent `?

2023-10-20 09:59 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMInput/TMInput.xaml.cs
>      internal void ToggleRightIconState(bool enabledState)
Do we need these methods at all?

2023-10-20 12:37 UTC, ElishaSamPeterPrabhu commented on Trimble.Modus.Components/Controls/TMInput/TMInput.xaml.cs
>      internal void ToggleRightIconState(bool enabledState)
Yes, a bit modified for number input

2023-10-20 12:38 UTC, ElishaSamPeterPrabhu commented on Trimble.Modus.Components/Controls/TMInput/TMInput.xaml
> +                 Content="{Binding RightCustomContent}">
Changed to RightView and left view

2023-10-20 12:39 UTC, ElishaSamPeterPrabhu commented
@rthanga1 For the left view and right view the name for the commands are still left icon and right icon commands as usually icons only serve purpose for a command , or should we change it?

2023-10-24 06:32 UTC, rthanga1 commented
> @rthanga1 For the left view and right view the name for the commands are still left icon and right icon commands as usually icons only serve purpose for a command , or should we change it?

@ElishaSamPeterPrabhu We don't even need those commands.

2023-10-24 06:46 UTC, ElishaSamPeterPrabhu commented
> > @rthanga1 For the left view and right view the name for the commands are still left icon and right icon commands as usually icons only serve purpose for a command , or should we change it?
> 
> @ElishaSamPeterPrabhu We don't even need those commands. 

@rthanga1 I added those commands since , number input inherits the inner borderless entry , left and right icons form TMInput .

2023-10-24 09:24 UTC, rthanga1 commented
I am still thinking we should somehow support just the iconsource along with the left/right views. I will checkout this tonight and update you if anything can be improved. Otherwise I will approve this PR.

2023-10-24 15:30 UTC, rthanga1 approved these changes

2023-10-25 05:08 UTC, ElishaSamPeterPrabhu commented
Modify password icon to a functional one
![Screenshot_1698210455](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/e5021113-9a96-43dc-a62b-067dd5cec8e8)
![Screenshot_1698210453](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/161af368-5a08-4991-a56e-9067b0d34962)

2023-10-25 10:14 UTC, rthanga1 approved these changes

2023-10-25 10:20 UTC, merged