Alert control
trimble-oss/modus-mobile-maui-components pull request #306
Opened 2023-11-24 04:34 UTC by BAL4-R

Added Alert Control, closes #25

![Simulator Screenshot - iPhone 15 - 2023-11-24 at 10 00 49](https://github.com/trimble-oss/modus-mobile-maui-components/assets/130034598/ca5b85d3-95c6-4be4-86c3-4e88ddca875e)
![simulator_screenshot_ED126E00-CDC4-4CB2-98D8-6A61EBCE8F25](https://github.com/trimble-oss/modus-mobile-maui-components/assets/130034598/39d599be-7bdd-45f6-b1d5-c6e4704720b9)

2023-11-27 05:24 UTC, rthanga1 approved these changes

2023-11-29 06:14 UTC, ElishaSamPeterPrabhu requested changes
Background Color Is being applied according to dark theme but the icons are different from figma
Success :
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/a3cb5899-87e8-422c-961c-2bcf7ba53c70)
Error :
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/d948c84c-44f7-47ef-be94-65b6c710e0df)
Warning :
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/dabdd69f-50a8-480f-95da-243f4e5de308)
Primary :
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/09b11e88-fc0d-410c-8669-e6c1dde37042)
Secondary :
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/239a3dbc-a688-4a12-bbbd-93fb937bef55)
Dark :
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/95643962-d90f-47e4-959a-0e703e6bb4dc)
Expected :
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/3d63315d-2121-4771-95d9-992c9f736001)

2023-12-01 10:25 UTC, rthanga1 commented on DemoApp/DemoApp/Views/AlertSamplePage.xaml
> +      <Button Text="Show"
Use the modus button and modus switches in this page?

2023-12-01 10:27 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMAlert/TMAlert.xaml
> +        <BoxView x:Name="VerticalSeparator"
If you look closely there's a spacing in left and top of the separator.

<img width="777" alt="Screen Shot 2023-12-01 at 3 56 51 PM" src="https://github.com/trimble-oss/modus-mobile-maui-components/assets/60956922/0d022f65-a1f3-46f5-a6eb-342f6c2e1704">

2023-12-01 10:28 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMAlert/TMAlert.xaml
> +      <Grid VerticalOptions="FillAndExpand"
Why do we need 2 grids? Can't achieve the same with just one grid?

2023-12-01 10:32 UTC, rthanga1 commented on Trimble.Modus.Components/Images/alert_error_icon.svg
We are facing issues when the user adds another image with the same name. E.g  #307. Can you add a prefix 'modus' to these images? like "modus_alert_error_icon.svg". Let me know if you find any other solution for this.

2023-12-08 07:47 UTC, rthanga1 submitted a review, later dismissed

2023-12-08 09:00 UTC, ElishaSamPeterPrabhu approved these changes

2023-12-08 09:04 UTC, merged