Support Dark Theme in Chips
trimble-oss/modus-mobile-maui-components pull request #308
Opened 2023-11-29 09:18 UTC by pooja-ps-trimble

2023-11-29 09:51 UTC, rthanga1 submitted a review, later dismissed

2023-12-01 11:16 UTC, rthanga1 requested changes

2023-12-01 11:16 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMChips/TMChips.xaml
> -  <Border x:Name="frame"
Icon colors should change along with the text color in dark theme (i.e should be in white)

![Simulator Screen Shot - iPhone 14 - 2023-12-01 at 16 45 06](https://github.com/trimble-oss/modus-mobile-maui-components/assets/60956922/1b6475ab-d4c2-4ad8-a162-9d7afd50014f)

2023-12-01 11:52 UTC, pooja-ps-trimble commented on Trimble.Modus.Components/Controls/TMChips/TMChips.xaml.cs
> +        frame.BackgroundColor = this.BackgroundColor;
Sure. I will update.
I saw the a similar approach being followed in TMButton and TMBadge, hence went with this.

2023-12-01 12:07 UTC, rthanga1 submitted a review, later dismissed

2023-12-08 07:51 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMChips/TMChips.xaml.cs
> +        frame.BackgroundColor = this.BackgroundColor;
@pooja-ps-trimble is this addressed?

2023-12-08 17:16 UTC, ElishaSamPeterPrabhu submitted a review, later dismissed

2023-12-11 12:57 UTC, merged