Dark theme for segmented control - #299
trimble-oss/modus-mobile-maui-components pull request #312
Opened 2023-12-01 09:15 UTC by BAL4-R

Added dark theme for segmented control, closes #299 

Screenshot:
<img width="646" alt="Screenshot 2023-12-01 at 2 43 09 PM" src="https://github.com/trimble-oss/modus-mobile-maui-components/assets/130034598/6a8aa4af-f5d5-4468-934c-e02c6d11e893">

2023-12-01 10:51 UTC, Sofiya-kumar requested changes

2023-12-01 10:51 UTC, Sofiya-kumar commented on Trimble.Modus.Components/Controls/TMSegmentedControl/TMSegmentedItem.xaml.cs
> +        {
Can you add as a method

2023-12-01 10:51 UTC, Sofiya-kumar commented on Trimble.Modus.Components/Styles/DarkTheme.xaml
> +
Can you remove these extra spaces that followed in other controls colors as well?

2023-12-01 11:07 UTC, rthanga1 requested changes

2023-12-01 11:07 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMSegmentedControl/TMSegmentedItem.xaml.cs
> +        string baseStyle = (ColorTheme == SegmentColorTheme.Primary) ? "Primary" : "Secondary";
Can you try the VisualStateManager like in the other control for toggling b/w Normal and Selected?

2023-12-01 11:08 UTC, rthanga1 commented
Also getting an error in the console while opening the SegmentControl page

`Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'
Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'
Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'
Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'
`

2023-12-01 11:09 UTC, rthanga1 requested changes

2023-12-01 11:09 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMSegmentedControl/TMSegmentedItem.xaml
> +﻿<?xml version="1.0" encoding="utf-8"?>
Getting this error in the console

`Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'
Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'
Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'
Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert [Color: Red=0, Green=0.3882353, Blue=0.6392157, Alpha=1] to type 'Microsoft.Maui.Controls.Style'

`

2023-12-08 08:41 UTC, rthanga1 approved these changes

2023-12-08 08:41 UTC, rthanga1 commented on Trimble.Modus.Components/Controls/TMSegmentedControl/TMSegmentedItem.xaml
> +﻿<?xml version="1.0" encoding="utf-8"?>
To check later. @BAL4-R Can you create a tech debt issue for this? We can close this one for now.

2023-12-08 10:55 UTC, rthanga1 approved these changes

2023-12-08 11:43 UTC, rthanga1 approved these changes

2023-12-08 11:43 UTC, merged