Add basic popup overlay control
trimble-oss/modus-mobile-maui-components pull request #69
Opened 2023-05-19 09:00 UTC by BAL4-R

Resolves #49 
Create basic popup overlay control to add dynamic content into a popup overlay

2023-05-19 09:11 UTC, rthanga1 requested changes

2023-05-19 09:11 UTC, rthanga1 commented on DemoApp/DemoApp/MauiProgram.cs
> +            .ConfigurePopups()
The entire popup related logic should not be exposed to the clients

2023-05-19 09:11 UTC, rthanga1 commented on DemoApp/DemoApp/MainPage.xaml.cs
> +﻿using Trimble.Modus.Components.Overlay.Services;
Please rename 'Overlay' namespace into 'Popup'

2023-05-19 11:08 UTC, BAL4-R commented on Trimble.Modus.Components/Controls/Overlay/Animations/FadeAnimation.cs
> +public class FadeAnimation : BaseAnimation
Done

2023-05-19 11:08 UTC, BAL4-R commented on DemoApp/DemoApp/MainPage.xaml.cs
> +﻿using Trimble.Modus.Components.Overlay.Services;
Done

2023-05-21 05:15 UTC, rthanga1 approved these changes

2023-05-21 09:48 UTC, rthanga1 commented on .github/workflows/ci.yaml
@jeffdoolittle I made some change to the ci.yaml file. There's still a lot to do, but this fixes the build failures. Please go over my changes and let me know if this is okay.

2023-05-22 04:33 UTC, merged