Feature/78 toast
trimble-oss/modus-mobile-maui-components pull request #84
Opened 2023-05-30 10:21 UTC by ElishaSamPeterPrabhu

2023-05-30 12:09 UTC, ElishaSamPeterPrabhu commented
pc Screenshots toast
![pc1](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/da689a92-890a-4b64-953b-fed3fd8d41d8)
![pc2](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/88e882f4-915b-4e7e-9887-3f0ea074bfd0)

2023-05-30 12:32 UTC, Sofiya-kumar requested changes

2023-05-31 05:07 UTC, ElishaSamPeterPrabhu commented on Trimble.Modus.Components/Images/danger.png
Svg icons are unable to load hence, we are converting them to pngs amd using them

2023-05-31 05:10 UTC, ElishaSamPeterPrabhu commented on Trimble.Modus.Components/Themes/Colours.xaml
> +    <Color x:Key="Primary">#DCEDF9</Color>
Colors are duplicated but the key we are using will help us to identify the purpose of using that color and match them easily with the themes mentioned in figma ,hence we have separate colors keys for toast.

2023-05-31 06:36 UTC, ElishaSamPeterPrabhu commented
> @ElishaSamPeterPrabhu I have made some alignment fixes for iOS and also moved the close and action button to the xaml. Please run and check before merging. Please check Sofia's comment too

@rthanga1 Modified some padding and margin to fix alignment .Can you run it in iOS before merging?

2023-05-31 13:59 UTC, merged

2023-05-31 14:10 UTC, coliff commented on Trimble.Modus.Components/Themes/Colours.xaml
> +    <Color x:Key="Primary">#DCEDF9</Color>
Related - We should rename `colours.xaml` to `colors.xaml` for consistency. We should always use US English where possible.